multiple_select/config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :roles

  map.resources :users

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

multiple_select/app/models/role.rb
class Role < ActiveRecord::Base
  #has_and_belongs_to_many :user, :class_name => "User"
end

multiple_select/app/models/roles_users.rb
class RolesUsers < ActiveRecord::Base
end

multiple_select/app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :role, :class_name => "Role", :join_table => 'roles_users', :foreign_key=>'user_id', :association_foreign_key=>'role_id'

end

multiple_select/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end
end

multiple_select/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @roles = Role.find(:all)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

multiple_select/app/helpers/roles_helper.rb
module RolesHelper
end

multiple_select/app/helpers/users_helper.rb
module UsersHelper
end

multiple_select/app/views/roles/edit.html.erb
<h1>Editing role</h1>

<% form_for(@role) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :role_name %><br />
    <%= f.text_field :role_name %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

multiple_select/app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Role name</th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%=h role.role_name %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New role', new_role_path %>

multiple_select/app/views/roles/new.html.erb
<h1>New role</h1>

<% form_for(@role) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :role_name %><br />
    <%= f.text_field :role_name %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', roles_path %>

multiple_select/app/views/roles/show.html.erb
<p>
  <b>Role name:</b>
  <%=h @role.role_name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

multiple_select/app/views/users/edit.html.erb
<h1>Editing user</h1>

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

multiple_select/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>User name</th>
    <th>Password</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=h user.first_name %></td>
    <td><%=h user.last_name %></td>
    <td><%=h user.user_name %></td>
    <td><%=h user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>

multiple_select/app/views/users/new.html.erb
<h1>New user</h1>

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </p>

  <p>

    <%= collection_select(:user, :role_ids, @roles, :id, :role_name,{ :selected => @user.role_ids },{:multiple => true }) %>

  </p>


  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

multiple_select/app/views/users/show.html.erb
<p>
  <b>First name:</b>
  <%=h @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%=h @user.last_name %>
</p>

<p>
  <b>User name:</b>
  <%=h @user.user_name %>
</p>

<p>
  <b>Password:</b>
  <%=h @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>